<Project>
    <PropertyGroup>
        <UseWpf>true</UseWpf>
        <UseWindowsForms>true</UseWindowsForms>
        <Nullable>disable</Nullable>
        <ImplicitUsings>disable</ImplicitUsings>
        <GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
        <EmbeddedResourceUseDependentUponConvention>true</EmbeddedResourceUseDependentUponConvention>
        <LangVersion>default</LangVersion>
        <TargetFramework>net48</TargetFramework>
        <IsPackable>false</IsPackable>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>
</Project>