using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace OpenDentBusiness {
	
	public class GetAccountGuarantorResponse {

		
		public long AccountGuarantorNum { get; set; }

		
		public string Description { get; set; }

		
		public string ExternalID { get; set; }

	}
}
