<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <RootNamespace>OpenDental</RootNamespace>
        <OutputType>WinExe</OutputType>
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
    </PropertyGroup>

    <ItemGroup>
        <Reference Include="System.Web"/>
        <Reference Include="System.Web.Extensions"/>
        <Reference Include="System.Web.Services"/>
        <Reference Include="System.Speech"/>
        <Reference Include="System.Design"/>
        <Reference Include="System.IO.Compression"/>
        <Reference Include="System.Data.DataSetExtensions"/>
        <Reference Include="CDT">
            <HintPath>..\..\lib\CDT.dll</HintPath>
        </Reference>
        <Reference Include="DpsPos, Version=1.0.6191.28914, Culture=neutral, PublicKeyToken=fed6c2461985275f, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\..\lib\DpsPos.dll</HintPath>
        </Reference>
        <Reference Include="Health.Direct.Common">
            <HintPath>..\..\lib\Health.Direct.Common.dll</HintPath>
        </Reference>
        <Reference Include="ImagingDeviceManager">
            <HintPath>..\..\lib\ImagingDeviceManager.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.Office.Interop.Word, Version=15.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <EmbedInteropTypes>True</EmbedInteropTypes>
            <HintPath>..\..\lib\Microsoft.Office.Interop.Word.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.Web.WebView2.Core, Version=1.0.2420.47, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\..\lib\Microsoft.Web.WebView2.Core.dll</HintPath>
        </Reference>
        <Reference Include="Microsoft.Web.WebView2.WinForms, Version=1.0.2420.47, Culture=neutral, PublicKeyToken=2a8ab48044d2601e, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\..\lib\Microsoft.Web.WebView2.WinForms.dll</HintPath>
        </Reference>
        <Reference Include="MigraDoc.DocumentObjectModel, Version=1.2.2546.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\..\lib\MigraDoc.DocumentObjectModel.dll</HintPath>
        </Reference>
        <Reference Include="MigraDoc.Rendering, Version=1.2.2546.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\..\lib\MigraDoc.Rendering.dll</HintPath>
        </Reference>
        <Reference Include="MySqlConnector">
            <HintPath>..\..\lib\MySqlConnector.dll</HintPath>
        </Reference>
        <Reference Include="Newtonsoft.Json, Version=9.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\..\lib\Newtonsoft.Json.dll</HintPath>
        </Reference>
        <Reference Include="PdfSharp, Version=1.2.1269.0, Culture=neutral, PublicKeyToken=f94615aa0424f9eb, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\..\lib\PdfSharp.dll</HintPath>
        </Reference>
        <Reference Include="SharpDX, Version=4.0.1.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1, processorArchitecture=MSIL">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\..\lib\SharpDX.dll</HintPath>
        </Reference>
        <Reference Include="Tao.Platform.Windows, Version=1.0.0.3, Culture=neutral, PublicKeyToken=701104b2da67a104">
            <SpecificVersion>False</SpecificVersion>
            <HintPath>..\..\lib\Tao.Platform.Windows.dll</HintPath>
        </Reference>
        <Reference Include="xImageDeviceManager">
            <HintPath>..\..\lib\xImageDeviceManager.dll</HintPath>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OpenDental.Core\OpenDental.Core.csproj"/>
        <ProjectReference Include="..\OpenDental.Chart\OpenDental.Chart.csproj"/>
        <ProjectReference Include="..\OpenDental.Wpf\OpenDental.Wpf.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0"/>
        <PackageReference Include="LanguageExt.Core" Version="4.4.9" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.1" />
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Forms\FormCalendar.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FormCanadaSummaryReconciliation.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FormCarrierCombine.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FormChartViewDateFilter.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FormClaimResend.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Features\Providers\Forms\FormProvAdditional.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Features\Providers\Forms\FormProvEdit.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Features\Providers\Forms\FormProviderMerge.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Features\Providers\Forms\FormProviderMultiPick.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Features\Providers\Forms\FormProviderSetup.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FormPerioEdit.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FormDunningSetup.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FormDunningEdit.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FormContactEdit.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Features\FormClaimPayList.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="Forms\FormClaimPayList.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

</Project>