<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateResourceUsePreserializedResources>false</GenerateResourceUsePreserializedResources>
        <EmbeddedResourceUseDependentUponConvention>false</EmbeddedResourceUseDependentUponConvention>
    </PropertyGroup>
    
    <ItemGroup>
        <Reference Include="SharpDX">
            <HintPath>..\..\lib\SharpDX.dll</HintPath>
        </Reference>
        <Reference Include="SharpDX.Direct3D9">
            <HintPath>..\..\lib\SharpDX.Direct3D9.dll</HintPath>
        </Reference>
        <Reference Include="SharpDX.Mathematics">
            <HintPath>..\..\lib\SharpDX.Mathematics.dll</HintPath>
        </Reference>
        <Reference Include="Tao.OpenGl, Version=2.1.0.4, Culture=neutral, PublicKeyToken=1ca010269a4501ef, processorArchitecture=MSIL">
            <HintPath>..\..\lib\Tao.OpenGl.dll</HintPath>
            <SpecificVersion>False</SpecificVersion>
        </Reference>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\OpenDental.Core\OpenDental.Core.csproj"/>
    </ItemGroup>

    <ItemGroup>
        <EmbeddedResource Update="Properties\Resources.resx">
            <Generator>ResXFileCodeGenerator</Generator>
            <LastGenOutput>Resources.Designer.cs</LastGenOutput>
        </EmbeddedResource>
        <None Remove="Resources\**"/>
        <EmbeddedResource Include="Resources\**"/>
    </ItemGroup>

    <ItemGroup>
        <Compile Update="Properties\Resources.Designer.cs">
            <DesignTime>True</DesignTime>
            <AutoGen>True</AutoGen>
            <DependentUpon>Resources.resx</DependentUpon>
        </Compile>
    </ItemGroup>

</Project>