namespace OpenDental.UI;

public class Gen_PatAdd
{
    public static string GetBase64()
    {
        return "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAACXBIWXMAAAsSAAALEgHS3X78AAAA9UlEQVQ4je2UsQ3CMBBFf1CoYQAXQfIQlGEDRsgGpHRH6FwyQkZgA+igZABLUHiAUKcIuihBEQRydgUSv4rvvp4d3/mCqqrgIyXFEkDaCW21sbt24QVWUmwBrHpSG21s1gsej091oCznwRtoBODyYd+ZNvY6cj4uEHHyPmCWfMBXTj4IwyOret07V1JQgdY9tkfxQsfTtqKuOD+3G4BDu/DpihxADCDTxuadeEIxgmtjEyewkoKAe8YfLVyLlzI8tc8VHHN9L8V7d7eNJkzw5KseyB/8o+Ab1+cKpnkwBKf866wYkpJi2mxAr5C+WxXNdMu1scUdDolWXncokbUAAAAASUVORK5CYII=";
    }
}