namespace OpenDental.UI;

public class Gen_Video
{
    public static string GetBase64()
    {
        return "iVBORw0KGgoAAAANSUhEUgAAABYAAAAWCAYAAADEtGw7AAAACXBIWXMAAAsSAAALEgHS3X78AAAAlUlEQVQ4jWP8//8/Ay0AE01MHTUYGbCA2K42uhMYGBjyydA/cfeRywXYJBhdrHUSGBgY5lPguMTdRy4vcLXRDWBgYAA5cAGIBhl8gIGBwZ4Cg08yMDD8QDPjIAsFBsKAOTbB0XQ8wg0GJbeD2AxeQKHBM3YfuezAwMAQyMDA8BCUGxkYGALA5TFNsvRoQT9EDWZgYAAAGsEm5/eBFBsAAAAASUVORK5CYII=";
    }
}