using System;
using System.Collections.Generic;
using DataConnectionBase;
using Imedisoft.Core.Caching;
using Imedisoft.Core.Crud;
using Imedisoft.Core.Entities;

namespace OpenDentBusiness;

public class Encounters
{
    public static List<Encounter> Refresh(long patNum)
    {
        var command = "SELECT * FROM encounter WHERE PatNum = " + SOut.Long(patNum) + " ORDER BY DateEncounter";
        return EncounterCrud.SelectMany(command);
    }

    public static void InsertDefaultEncounter(long patNum, long provNum, DateTime date)
    {
        //Validate prefs. If they are not set, we have nothing to insert so no reason to check.
        if (PrefC.GetString(PrefName.CQMDefaultEncounterCodeSystem) == "" || PrefC.GetString(PrefName.CQMDefaultEncounterCodeValue) == "none") return;
        //If no encounter for date for this patient
        var command = "SELECT COUNT(*) NumEncounters FROM encounter WHERE encounter.PatNum=" + SOut.Long(patNum) + " "
                      + "AND encounter.DateEncounter=" + SOut.Date(date) + " "
                      + "AND encounter.ProvNum=" + SOut.Long(provNum);
        var count = SIn.Int(Db.GetCount(command));
        if (count > 0) //Encounter already exists for date
            return;
        //Insert encounter with default encounter code system and code value set in Setup>EHR>Settings
        var encounter = new Encounter();
        encounter.PatNum = patNum;
        encounter.ProvNum = provNum;
        encounter.DateEncounter = date;
        encounter.CodeSystem = PrefC.GetString(PrefName.CQMDefaultEncounterCodeSystem);
        encounter.CodeValue = PrefC.GetString(PrefName.CQMDefaultEncounterCodeValue);
        Insert(encounter);
    }

    public static long InsertEncsFromProcDates(DateTime startDate, DateTime endDate, string codeValue, string codeSystem)
    {
        var command = "INSERT INTO encounter (PatNum,ProvNum,CodeValue,CodeSystem,Note,DateEncounter) "
                      + "(SELECT PatNum,ProvNum,'" + SOut.String(codeValue) + "','" + SOut.String(codeSystem) + "',"
                      + "'Encounter auto-generated by Open Dental based on completed procedure information.',ProcDate "
                      + "FROM procedurelog "
                      + "WHERE ProcStatus=2 "
                      + "AND ProcDate BETWEEN " + SOut.Date(startDate) + " AND " + SOut.Date(endDate) + " "
                      + "AND NOT EXISTS(" //Don't insert if there's already an encounter with this code for this pat,prov,date
                      + "SELECT * FROM encounter "
                      + "WHERE encounter.PatNum=procedurelog.PatNum "
                      + "AND encounter.ProvNum=procedurelog.ProvNum "
                      + "AND encounter.DateEncounter=procedurelog.ProcDate "
                      + "AND encounter.CodeValue='" + SOut.String(codeValue) + "' "
                      + "AND encounter.CodeSystem='" + SOut.String(codeSystem) + "') "
                      + "GROUP BY PatNum,ProvNum,ProcDate)";
        return Db.NonQ(command);
    }
    
    public static void Insert(Encounter encounter)
    {
        EncounterCrud.Insert(encounter);
    }
    
    public static void Update(Encounter encounter)
    {
        EncounterCrud.Update(encounter);
    }
    
    public static void Delete(long encounterNum)
    {
        var command = "DELETE FROM encounter WHERE EncounterNum = " + SOut.Long(encounterNum);
        Db.NonQ(command);
    }
}