using OpenDentBusiness;

namespace Imedisoft.Core.Entities;

public class ProcButton : TableBase
{
    [CrudColumn(IsPriKey = true)]
    public long ProcButtonNum;

    public string Description;
    public int ItemOrder;

    ///<summary>FK to definition.DefNum.</summary>
    public long Category;

    ///<summary>If no image, then the clob will be an empty string.  In this case, the bitmap will be null when loaded from the database.</summary>
    public string ButtonImage;

    ///<summary>Only useful for procedure buttons which cause more than one procedure to be charted.  Example: Crown (D code) and Delivery (N code).
    ///Causes the procedures generated by this procedure button to be grouped using links in the procmultivisit table.</summary>
    public bool IsMultiVisit;

    public ProcButton Copy()
    {
        return (ProcButton) MemberwiseClone();
    }
}