//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace OpenDentBusiness.PayConnectService {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9032.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MerchantServiceInstancePortBinding", Namespace="dxci.merchant")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Response))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transRequest))]
    public partial class MerchantService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        private bool useDefaultCredentialsSetExplicitly;
  
        public MerchantService() {
            this.Url = global::OpenDentBusiness.Properties.Settings.Default.OpenDentBusiness_PayConnectService_MerchantService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }

        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="dxci.merchant", ResponseNamespace="dxci.merchant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isValidCard([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string number) {
            object[] results = this.Invoke("isValidCard", new object[] {
                        number});
            return ((bool)(results[0]));
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="dxci.merchant", ResponseNamespace="dxci.merchant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("transResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public transResponse processCreditCard([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Credentials credentials, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] creditCardRequest request) {
            object[] results = this.Invoke("processCreditCard", new object[] {
                        credentials,
                        request});
            return ((transResponse)(results[0]));
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="dxci.merchant", ResponseNamespace="dxci.merchant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("signatureResponse", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public signatureResponse processSignature([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] Credentials credentials, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] signatureRequest request) {
            object[] results = this.Invoke("processSignature", new object[] {
                        credentials,
                        request});
            return ((signatureResponse)(results[0]));
        }
        
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="dxci.merchant", ResponseNamespace="dxci.merchant", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool isValidExpiration([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] expiration expiration) {
            object[] results = this.Invoke("isValidExpiration", new object[] {
                        expiration});
            return ((bool)(results[0]));
        }

        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.common")]
    public partial class Credentials {
        
        private string clientField;
        private string serviceIDField;
        private string usernameField;
        private string passwordField;
        private string versionField;
        
        public string Client {
            get {
                return this.clientField;
            }
            set {
                this.clientField = value;
            }
        }
        
        public string ServiceID {
            get {
                return this.serviceIDField;
            }
            set {
                this.serviceIDField = value;
            }
        }
        
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
            }
        }
        
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
            }
        }

        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class signatureRequest {
        
        private signatureType signatureTypeField;
        private string signatureDataField;
        private string refNumberField;
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public signatureType SignatureType {
            get {
                return this.signatureTypeField;
            }
            set {
                this.signatureTypeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SignatureData {
            get {
                return this.signatureDataField;
            }
            set {
                this.signatureDataField = value;
            }
        }
        
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RefNumber {
            get {
                return this.refNumberField;
            }
            set {
                this.refNumberField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public enum signatureType {
        
        BMP,
        JPEG,
        TIFF,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.common")]
    public partial class Status {
        
        private int codeField;
        private string descriptionField;
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
            }
        }
        
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(merchantInfoResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(batchInfoResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(signatureResponse))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Token))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(transResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.common")]
    public abstract partial class Response {
        
        private Status statusField;
        private string[] messagesField;
        
        /// <remarks/>
        public Status Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Message", IsNullable=false)]
        public string[] Messages {
            get {
                return this.messagesField;
            }
            set {
                this.messagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class merchantInfoResponse : Response {
        
        private bool forceDuplicatesField;
        
        private bool autoCloseBatchField;
        
        private bool echeckField;
        
        private cardType[] acceptedCardsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ForceDuplicates {
            get {
                return this.forceDuplicatesField;
            }
            set {
                this.forceDuplicatesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool AutoCloseBatch {
            get {
                return this.autoCloseBatchField;
            }
            set {
                this.autoCloseBatchField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool Echeck {
            get {
                return this.echeckField;
            }
            set {
                this.echeckField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("AcceptedCard", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public cardType[] AcceptedCards {
            get {
                return this.acceptedCardsField;
            }
            set {
                this.acceptedCardsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public enum cardType {
        
        /// <remarks/>
        VISA,
        
        /// <remarks/>
        MASTERCARD,
        
        /// <remarks/>
        AMEX,
        
        /// <remarks/>
        DISCOVER,
        
        /// <remarks/>
        DINERS,
        
        /// <remarks/>
        JCB,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class batchInfoResponse : Response {
        
        private decimal netAmountField;
        
        private bool netAmountFieldSpecified;
        
        private int netCountField;
        
        private decimal creditSaleAmountField;
        
        private bool creditSaleAmountFieldSpecified;
        
        private int creditSaleCountField;
        
        private decimal creditReturnAmountField;
        
        private bool creditReturnAmountFieldSpecified;
        
        private int creditReturnCountField;
        
        private decimal creditNetAmountField;
        
        private bool creditNetAmountFieldSpecified;
        
        private int creditNetCountField;
        
        private decimal debitSaleAmountField;
        
        private bool debitSaleAmountFieldSpecified;
        
        private int debitSaleCountField;
        
        private decimal debitReturnAmountField;
        
        private bool debitReturnAmountFieldSpecified;
        
        private int debitReturnCountField;
        
        private decimal debitNetAmountField;
        
        private bool debitNetAmountFieldSpecified;
        
        private int debitNetCountField;
        
        private decimal ebtSaleAmountField;
        
        private bool ebtSaleAmountFieldSpecified;
        
        private int ebtSaleCountField;
        
        private decimal ebtReturnAmountField;
        
        private bool ebtReturnAmountFieldSpecified;
        
        private int ebtReturnCountField;
        
        private decimal ebtNetAmountField;
        
        private bool ebtNetAmountFieldSpecified;
        
        private int ebtNetCountField;
        
        private decimal checkSaleAmountField;
        
        private bool checkSaleAmountFieldSpecified;
        
        private int checkSaleCountField;
        
        private decimal checkNetAmountField;
        
        private bool checkNetAmountFieldSpecified;
        
        private int checkNetCountField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal NetAmount {
            get {
                return this.netAmountField;
            }
            set {
                this.netAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NetAmountSpecified {
            get {
                return this.netAmountFieldSpecified;
            }
            set {
                this.netAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int NetCount {
            get {
                return this.netCountField;
            }
            set {
                this.netCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CreditSaleAmount {
            get {
                return this.creditSaleAmountField;
            }
            set {
                this.creditSaleAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreditSaleAmountSpecified {
            get {
                return this.creditSaleAmountFieldSpecified;
            }
            set {
                this.creditSaleAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CreditSaleCount {
            get {
                return this.creditSaleCountField;
            }
            set {
                this.creditSaleCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CreditReturnAmount {
            get {
                return this.creditReturnAmountField;
            }
            set {
                this.creditReturnAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreditReturnAmountSpecified {
            get {
                return this.creditReturnAmountFieldSpecified;
            }
            set {
                this.creditReturnAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CreditReturnCount {
            get {
                return this.creditReturnCountField;
            }
            set {
                this.creditReturnCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CreditNetAmount {
            get {
                return this.creditNetAmountField;
            }
            set {
                this.creditNetAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CreditNetAmountSpecified {
            get {
                return this.creditNetAmountFieldSpecified;
            }
            set {
                this.creditNetAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CreditNetCount {
            get {
                return this.creditNetCountField;
            }
            set {
                this.creditNetCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DebitSaleAmount {
            get {
                return this.debitSaleAmountField;
            }
            set {
                this.debitSaleAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebitSaleAmountSpecified {
            get {
                return this.debitSaleAmountFieldSpecified;
            }
            set {
                this.debitSaleAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DebitSaleCount {
            get {
                return this.debitSaleCountField;
            }
            set {
                this.debitSaleCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DebitReturnAmount {
            get {
                return this.debitReturnAmountField;
            }
            set {
                this.debitReturnAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebitReturnAmountSpecified {
            get {
                return this.debitReturnAmountFieldSpecified;
            }
            set {
                this.debitReturnAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DebitReturnCount {
            get {
                return this.debitReturnCountField;
            }
            set {
                this.debitReturnCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal DebitNetAmount {
            get {
                return this.debitNetAmountField;
            }
            set {
                this.debitNetAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DebitNetAmountSpecified {
            get {
                return this.debitNetAmountFieldSpecified;
            }
            set {
                this.debitNetAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int DebitNetCount {
            get {
                return this.debitNetCountField;
            }
            set {
                this.debitNetCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal EbtSaleAmount {
            get {
                return this.ebtSaleAmountField;
            }
            set {
                this.ebtSaleAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EbtSaleAmountSpecified {
            get {
                return this.ebtSaleAmountFieldSpecified;
            }
            set {
                this.ebtSaleAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int EbtSaleCount {
            get {
                return this.ebtSaleCountField;
            }
            set {
                this.ebtSaleCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal EbtReturnAmount {
            get {
                return this.ebtReturnAmountField;
            }
            set {
                this.ebtReturnAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EbtReturnAmountSpecified {
            get {
                return this.ebtReturnAmountFieldSpecified;
            }
            set {
                this.ebtReturnAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int EbtReturnCount {
            get {
                return this.ebtReturnCountField;
            }
            set {
                this.ebtReturnCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal EbtNetAmount {
            get {
                return this.ebtNetAmountField;
            }
            set {
                this.ebtNetAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EbtNetAmountSpecified {
            get {
                return this.ebtNetAmountFieldSpecified;
            }
            set {
                this.ebtNetAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int EbtNetCount {
            get {
                return this.ebtNetCountField;
            }
            set {
                this.ebtNetCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CheckSaleAmount {
            get {
                return this.checkSaleAmountField;
            }
            set {
                this.checkSaleAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckSaleAmountSpecified {
            get {
                return this.checkSaleAmountFieldSpecified;
            }
            set {
                this.checkSaleAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CheckSaleCount {
            get {
                return this.checkSaleCountField;
            }
            set {
                this.checkSaleCountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal CheckNetAmount {
            get {
                return this.checkNetAmountField;
            }
            set {
                this.checkNetAmountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CheckNetAmountSpecified {
            get {
                return this.checkNetAmountFieldSpecified;
            }
            set {
                this.checkNetAmountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int CheckNetCount {
            get {
                return this.checkNetCountField;
            }
            set {
                this.checkNetCountField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class signatureResponse : Response {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class Token : Response {
        
        private string tokenIdField;
        
        private expiration expirationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string TokenId {
            get {
                return this.tokenIdField;
            }
            set {
                this.tokenIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public expiration Expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class expiration {
        
        private int monthField;
        
        private int yearField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class transResponse : Response {
        
        private string authCodeField;
        
        private string refNumberField;
        
        private Token paymentTokenField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AuthCode {
            get {
                return this.authCodeField;
            }
            set {
                this.authCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RefNumber {
            get {
                return this.refNumberField;
            }
            set {
                this.refNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public Token PaymentToken {
            get {
                return this.paymentTokenField;
            }
            set {
                this.paymentTokenField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(debitCardRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(creditCardRequest))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(checkRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public abstract partial class transRequest {
        
        private transType transTypeField;
        
        private bool forceDuplicateField;
        
        private bool forceDuplicateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public transType TransType {
            get {
                return this.transTypeField;
            }
            set {
                this.transTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool ForceDuplicate {
            get {
                return this.forceDuplicateField;
            }
            set {
                this.forceDuplicateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ForceDuplicateSpecified {
            get {
                return this.forceDuplicateFieldSpecified;
            }
            set {
                this.forceDuplicateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public enum transType {
        
        /// <remarks/>
        SALE,
        
        /// <remarks/>
        AUTH,
        
        /// <remarks/>
        RETURN,
        
        /// <remarks/>
        VOID,
        
        /// <remarks/>
        FORCE,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class debitCardRequest : transRequest {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class creditCardRequest : transRequest {
        
        private string cardNumberField;
        
        private expiration expirationField;
        
        private string magDataField;
        private string nameOnCardField;
        
        private decimal amountField;
        private bool amountFieldSpecified;
        private string refNumberField;
        private string zipField;
        private string securityCodeField;
        private bool paymentTokenRequestedField;
        private bool paymentTokenRequestedFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string CardNumber {
            get {
                return this.cardNumberField;
            }
            set {
                this.cardNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public expiration Expiration {
            get {
                return this.expirationField;
            }
            set {
                this.expirationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string MagData {
            get {
                return this.magDataField;
            }
            set {
                this.magDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string NameOnCard {
            get {
                return this.nameOnCardField;
            }
            set {
                this.nameOnCardField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal Amount {
            get {
                return this.amountField;
            }
            set {
                this.amountField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AmountSpecified {
            get {
                return this.amountFieldSpecified;
            }
            set {
                this.amountFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string RefNumber {
            get {
                return this.refNumberField;
            }
            set {
                this.refNumberField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string Zip {
            get {
                return this.zipField;
            }
            set {
                this.zipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string SecurityCode {
            get {
                return this.securityCodeField;
            }
            set {
                this.securityCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool PaymentTokenRequested {
            get {
                return this.paymentTokenRequestedField;
            }
            set {
                this.paymentTokenRequestedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PaymentTokenRequestedSpecified {
            get {
                return this.paymentTokenRequestedFieldSpecified;
            }
            set {
                this.paymentTokenRequestedFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="dxci.merchant")]
    public partial class checkRequest : transRequest {
    }
}

#pragma warning restore 1591