using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace OpenDentBusiness {
	
	public class CreateAccessCodeRequest {

		
		public string EmailChainGuid { get; set; }

		
		public string EmailAddressGuid { get; set; }

		
		public bool ForceCreateNewCode { get; set; }

	}
}
