using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace OpenDentBusiness {
	
	public class GetEmailResponse {

		
		public EmailResource Email { get; set; }

		
		public EmailAddressResource ChainOwner { get; set; }

		
		public List<EmailAddressResource> ListEmailAddresses { get; set; }

	}
}
