using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace OpenDentBusiness {
	
	public class GetIdentityResponse {

		
		public IdentityResource IdentityResource { get; set; }

	}
}
