using System;
using System.Collections.Generic;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace OpenDentBusiness {
	///<summary>These must match Amazon's VerificationStatus class.</summary>
	public enum IdentityVerificationStatus {
		
		Failed,
		
		NotStarted,
		
		Pending,
		
		Success,
		
		TemporaryFailure,
	}
}
