using System;
using System.Collections.Generic;
using System.IO;

//This file is auto-generated by the 'SecureEmail.CodeGenerator'. Do not change.
namespace OpenDentBusiness {
	
	public class ValidateAccessCodeRequest {

		
		public string AccessCode { get; set; }

		
		public string AccessCodeGuid { get; set; }

	}
}
